# .github/workflows/ci.yml

name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get install g++ make

    - name: Build the C++ program
      run: make

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hello
        path: ./hello

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: hello

    - name: Push to Remote Server
      run: scp hello username@your_remote_server:/path/to/deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
