name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - test  # Run this on every push to the test branch
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    # Create a folder and move the hello.exe inside it
    - name: Create folder and move hello.exe
      run: |
        mkdir hello-folder
        move hello.exe hello-folder/

    # Upload the folder as an artifact
    - name: Upload hello-folder as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-folder-artifact
        path: ./hello-folder  # Upload the folder containing hello.exe

  deploy:
    needs: build
    runs-on: windows-latest  # Run the deployment on a Windows environment

    steps:
    - name: Download hello-folder artifact
      uses: actions/download-artifact@v3
      with:
        name: hello-folder-artifact  # Download the artifact (hello-folder)

    - name: Upload hello-folder to VPS using WinRM (HTTP)
      run: |
        winrm set winrm/config/client '@{AllowUnencrypted="true"}'
        Set-Item WSMan:\localhost\Client\TrustedHosts -Value "${{ secrets.VPS_IP }}" -Force

        $username = "${{ secrets.VPS_USER }}"
        $password = "${{ secrets.VPS_PASSWORD }}"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

        # Define the VPS IP and destination path on the VPS
        $vpsIp = "${{ secrets.VPS_IP }}"
        $destinationPath = "C:\\docker-test\\hello-folder"

        # Use WinRM to establish a session and copy the folder to the remote server (HTTP on port 5985)
        $session = New-PSSession -ComputerName $vpsIp -Credential $credential -Authentication Basic -Port 5985

        # Copy the hello-folder to the destination folder on the VPS
        Copy-Item -Path "./hello-folder/*" -Destination $destinationPath -ToSession $session -Recurse

        # Remove the session after the file transfer
        Remove-PSSession $session
      shell: pwsh
