# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe


  deploy:
    needs: build
    runs-on: windows-latest  # Run the deployment on a Windows environment

    steps:
    - name: Upload File to VPS via FTP with Base64 Authentication
      run: |
        # Encode username and password in Base64
        ENCODED_CREDS=$(echo -n "${{ secrets.VPS_USER }}:${{ secrets.VPS_PASSWORD }}" | base64)
        curl -T "./hello.exe" -H "Authorization: Basic $ENCODED_CREDS" "ftp://${{ secrets.VPS_IP }}/docker-test/hello.exe"
