name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - test  # Adjust to your branch if necessary
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Compile the C++ program using g++
    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    # Step 3: Create a folder and move the generated files (exe, dll) into it
    - name: Create folder and move generated files
      run: |
        mkdir hello-folder
        move hello.exe hello-folder/
        move *.dll hello-folder/ || echo "No DLL files found"
        echo "Listing contents of the current directory:"
        dir
        echo "Listing contents of hello-folder:"
        dir hello-folder
      shell: cmd

    # Step 4: Upload the folder as an artifact
    - name: Upload hello-folder as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-folder-artifact
        path: hello-folder  # Upload the folder containing hello.exe and dlls

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    # Step 1: Download the artifact (hello-folder)
    - name: Download hello-folder artifact
      uses: actions/download-artifact@v3
      with:
        name: hello-folder-artifact

    # Step 2: Verify the contents of the downloaded folder
    - name: List contents of the downloaded folder
      run: |
        echo "Listing contents of the current directory after downloading:"
        dir
        echo "Listing contents of hello-folder after downloading:"
        dir hello-folder
      shell: cmd
