# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Build the C++ application on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello
        path: ./hello.exe

  deploy:
    needs: build
    runs-on: ubuntu-latest  # Use a Linux runner to perform SCP

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: hello

    - name: Copy hello.exe to EC2 using SCP
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        scp -i id_rsa -o StrictHostKeyChecking=no ./hello.exe Administrator@ec2-3-18-112-50.us-east-2.compute.amazonaws.com:/C:/Udocker-test/hello.exe
