# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Build the C++ application on Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello
        path: ./hello.exe

    - name: Deploy to VPS
      env:
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        # Use PowerShell to copy files to the VPS and execute the .exe
        $session = New-PSSession -ComputerName $env:VPS_IP -Credential (New-Object System.Management.Automation.PSCredential("$env:VPS_USER", (ConvertTo-SecureString "$env:VPS_PASSWORD" -AsPlainText -Force)))
        Copy-Item -Path .\* -Destination 'C:\docker-test\' -ToSession $session
        Invoke-Command -Session $session -ScriptBlock {
            Start-Process "C:\docker-test\hello.exe"
        }
        Remove-PSSession -Session $session
