# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Copy hello.exe to VPS via SMB
      run: |
        $NetDrive = "Z"
        $NetShare = "\\${{ secrets.VPS_IP }}\docker-test"  # Path to the shared folder
        $username = "${{ secrets.VPS_USER }}"
        $password = "${{ secrets.VPS_PASSWORD }}"

        # Create the credential object
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

        # Map the network drive
        New-PSDrive -Name $NetDrive -PSProvider FileSystem -Root $NetShare -Credential $credential -Persist

        # Copy hello.exe to the shared folder
        Copy-Item -Path "./hello.exe" -Destination "$NetDrive\hello.exe"

        # Remove the mapped drive after copying
        Remove-PSDrive -Name Z
      shell: pwsh
