# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello
        path: ./hello.exe

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: hello

    - name: Use PowerShell Remoting to Copy hello.exe to EC2 Windows VM
      run: |
        $username = "Administrator"
        $password = "${{ secrets.SERVER_PASSWORD }}" | ConvertTo-SecureString -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ($username, $password)

        # Define the remote script to copy the file
        $remoteScript = {
            param ($file)
            Copy-Item -Path $file -Destination "C:\docker-test" -Force
        }

        # Invoke-Command to execute the file copy on the remote EC2 instance
        Invoke-Command -ComputerName "ec2-3-18-112-50.us-east-2.compute.amazonaws.com" -Credential $cred -ScriptBlock $remoteScript -ArgumentList "./hello.exe"
      shell: pwsh
