# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe


  deploy:
    needs: build
    runs-on: windows-latest  # Run the deployment on a Windows environment

    steps:
    - name: Upload Folder to VPS via FTP using PowerShell
      run: |
        $username = "${{ secrets.VPS_USER }}"
        $password = "${{ secrets.VPS_PASSWORD }}"
        $credentials = [System.Text.Encoding]::UTF8.GetBytes("${username}:${password}")
        $encodedCreds = [Convert]::ToBase64String($credentials)
  
        $folderPath = "./"
  
        Get-ChildItem -File -Recurse $folderPath | ForEach-Object {
          $filePath = $_.FullName
          $relativePath = $_.FullName.Substring($folderPath.Length + 1) # Get relative path of the file
          Write-Host "Uploading $filePath to ftp://${{ secrets.VPS_IP }}/docker-test/$relativePath"
          curl -T "$filePath" -H "Authorization: Basic $encodedCreds" "ftp://${{ secrets.VPS_IP }}/docker-test/$relativePath"
        }
      shell: pwsh
