# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Upload hello.exe to VPS via FTP
      run: |
        # Encode the credentials in PowerShell (Base64 encoding)
        $username = "${{ secrets.VPS_USER }}"
        $password = "${{ secrets.VPS_PASSWORD }}"
        $credentials = [System.Text.Encoding]::UTF8.GetBytes("${username}:${password}")
        $encodedCreds = [Convert]::ToBase64String($credentials)

        # Upload hello.exe to the docker-test folder on VPS
        Write-Host "Uploading hello.exe to ftp://${{ secrets.VPS_IP }}/docker-test/hello.exe"

        curl -T "./hello.exe" -H "Authorization: Basic $encodedCreds" "ftp://${{ secrets.VPS_IP }}/docker-test/hello.exe"
      shell: pwsh
