# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hello
        path: ./hello.exe  # Uploads the compiled binary (hello.exe)

  deploy:
    needs: build
    runs-on: windows-latest  # Run the deployment on a Windows environment

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: hello

    - name: Copy hello.exe to Windows VM using New-PSDrive
      run: |
        $username = "Administrator"
        $password = "${{ secrets.SERVER_PASSWORD }}" | ConvertTo-SecureString -AsPlainText -Force
        $cred = New-Object System.Management.Automation.PSCredential ($username, $password)

        # Map the network drive (Z:) to the remote path
        New-PSDrive -Name Z -PSProvider FileSystem -Root "\\3.18.112.50\C$\docker-test" -Credential $cred -Persist

        # Copy the file to the mapped drive without specifying credentials again
        Copy-Item -Path ./hello.exe -Destination Z:\hello.exe

        # Unmount the mapped network drive
        Remove-PSDrive -Name Z
      shell: pwsh
