# .github/workflows/ci.yml

name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build tools
      run: sudo apt-get install g++ make

    - name: Build the C++ program
      run: make

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hello
        path: ./hello

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v2
      with:
        name: hello

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Push to EC2 Server
      run: sshpass -p "${{ secrets.SERVER_PASSWORD }}" scp hello Administrator@ec2-3-18-112-50.us-east-2.compute.amazonaws.com:/C:/docker-test/
      env:
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
