# .github/workflows/ci.yml

name: Build and Push .exe to Windows VPS via WinRM

on:
  push:
    branches:
      - main  # Run this on every push to the main branch

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install MinGW
      run: |
        choco install mingw
        refreshenv

    - name: Compile C++ program
      run: |
        g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe
      shell: bash

    - name: Push .exe to Windows VPS via WinRM
      run: |
        $username = "${{ secrets.VPS_USER }}"  # Administrator or VPS user
        $password = "${{ secrets.VPS_PASSWORD }}"  # Password for the VPS user
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

        # VPS IP and target destination path
        $vpsIp = "${{ secrets.VPS_IP }}"
        $destinationPath = "C:\\Users\\Administrator\\hello.exe"  # Change path as necessary

        # Start a WinRM session to the VPS
        $session = New-PSSession -ComputerName $vpsIp -Credential $credential

        # Copy the compiled .exe to the VPS
        Copy-Item -Path "./hello.exe" -Destination $destinationPath -ToSession $session

        # Close the session
        Remove-PSSession $session
      shell: pwsh
