# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    - name: Upload hello.exe as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-exe
        path: ./hello.exe  # Upload hello.exe for later use in the deploy step

  deploy:
    needs: build
    runs-on: windows-latest  # Run the deployment on a Windows environment

    steps:
    - name: Download hello.exe artifact
      uses: actions/download-artifact@v3
      with:
        name: hello-exe  # Download the artifact (hello.exe)

    - name: Upload hello.exe to VPS using WinRM (HTTP)
      run: |
        winrm set winrm/config/client '@{AllowUnencrypted="true"}'
        Set-Item WSMan:\localhost\Client\TrustedHosts -Value "${{ secrets.VPS_IP }}" -Force

        $username = "${{ secrets.VPS_USER }}"
        $password = "${{ secrets.VPS_PASSWORD }}"
        $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

        # Define the VPS IP and destination path on the VPS
        $vpsIp = "${{ secrets.VPS_IP }}"
        $destinationPath = "C:\\docker-test\\hello.exe"

        # Use WinRM to establish a session and copy the file to the remote server (HTTP on port 5985)
        $session = New-PSSession -ComputerName $vpsIp -Credential $credential -Authentication Basic -Port 5985

        # Copy hello.exe to the destination folder on the VPS
        Copy-Item -Path "./hello.exe" -Destination $destinationPath -ToSession $session

        # Remove the session after the file transfer
        Remove-PSSession $session
      shell: pwsh
