# .github/workflows/ci.yml

name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - main  # Run this on every push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Run the build job on a Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe


  deploy:
    needs: build
    runs-on: windows-latest  # Run the deployment on a Windows environment

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: hello

    - name: Upload Folder to VPS via FTP
      env:
        FTP_SERVER: ${{ secrets.VPS_IP }}
        FTP_USER: ${{ secrets.VPS_USER }}
        FTP_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        curl -T "./*" ftp://$FTP_SERVER/C:/docker-test/ --user $FTP_USER:$FTP_PASSWORD
