name: C++ CI/CD Pipeline for Windows

on:
  push:
    branches:
      - test  # Adjust to your branch if necessary
  pull_request:
    branches:
      - test

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment

    steps:
    # Step 1: Checkout code from repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Compile the C++ program using g++
    - name: Build the C++ program using g++
      run: g++ -o hello.exe main.cpp  # This compiles main.cpp to hello.exe

    # Step 3: List all DLL files generated in the working directory
    - name: List all generated DLL and EXE files
      run: |
        echo "Listing all DLL and EXE files in the current working directory:"
        Get-ChildItem -Recurse -Filter *.dll  # List all DLL files
        Get-ChildItem -Recurse -Filter *.exe  # List the hello.exe file
      shell: pwsh

    # Step 4: Create a folder and move the generated files (exe, dll) into it
    - name: Create folder and move generated files
      run: |
        mkdir hello-folder
        move hello.exe hello-folder/
        move *.dll hello-folder/  # Move all DLL files to the folder if any are generated
        echo "Listing contents of hello-folder after moving files:"
        Get-ChildItem hello-folder
      shell: pwsh

    # Step 5: Upload the folder as an artifact
    - name: Upload hello-folder as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-folder-artifact
        path: ./hello-folder  # Upload the folder containing hello.exe and dlls

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    # Step 1: Download the artifact (hello-folder)
    - name: Download hello-folder artifact
      uses: actions/download-artifact@v3
      with:
        name: hello-folder-artifact

    # Step 2: Verify the contents of the downloaded folder
    - name: List contents of the downloaded folder
      run: |
        echo "Listing contents of hello-folder after downloading:"
        Get-ChildItem hello-folder  # List the contents of the folder
      shell: pwsh
